resource_manifest_version '44febabe-d386-4d18-afbe-5e627f4af937'
this_is_a_map 'yes'

data_file 'DLC_ITYP_REQUEST' 'stream/vw_prop_vw_accs.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/vw_prop_vw_accs_01.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/vw_prop_vw_animated_walls.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/vw_prop_vw_cabinets.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/vw_prop_vw_cards.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/vw_prop_vw_casino.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/vw_prop_vw_casinochips.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/vw_prop_vw_casino_art_01.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/vw_prop_vw_casino_art_02.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/vw_prop_vw_casino_art_03.ytyp'
data_file 'DLC_ITYP_REQUEST' 'vw_prop_vw_casino_art_04.ytyp'
data_file 'DLC_ITYP_REQUEST' 'vw_prop_vw_casino_art_05.ytyp'
data_file 'DLC_ITYP_REQUEST' 'vw_prop_vw_collectibles.ytyp'
data_file 'DLC_ITYP_REQUEST' 'vw_prop_vw_disposal.ytyp'
data_file 'DLC_ITYP_REQUEST' 'vw_prop_vw_door_break.ytyp'
data_file 'DLC_ITYP_REQUEST' 'vw_prop_vw_machinery.ytyp'
data_file 'DLC_ITYP_REQUEST' 'vw_prop_vw_screens.ytyp'
data_file 'DLC_ITYP_REQUEST' 'vw_prop_vw_storage.ytyp'
data_file 'DLC_ITYP_REQUEST' 'vw_prop_vw_tables.ytyp'
data_file 'DLC_ITYP_REQUEST' 'vw_prop_vw_turntable.ytyp'
